# Generated by Django 4.1.7 on 2023-02-17 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=20)),
                ('kcal', models.IntegerField(default=1)),
                ('category', models.CharField(max_length=30)),
                ('recipe', models.CharField(max_length=300)),
            ],
        ),
    ]
